### PR TITLE
Dataset description

### PR DESCRIPTION
**Pull request by cfkawa**
## Purpose

- Addresses Data curration 

## Type of change
- Documentation update

## Checklist
_Put an `x` in the boxes that apply._

- [ ] My code functions as intended
- [ ] I have used camelCase in my variable and function names
- [ ] I have commented my code properly
- [ ] I have provided the necessary prompts for automatic documentation
- [ ] I have provided a toy case under the examples folder
- [X] I have addressed all the issues entirely

### CODE REVIEW

**Comment by sahilbhola14** [comment]
Please run the pre-commit checks

**Comment by dorukaks** [comment]
No file extension is defined for any of the text files.

**Comment by dorukaks** [comment]
Suggestion: Before more work was done on this branch, I suggest that we close this PR and prune the branch `Data`. Then once we merge @sahilbhola14 's PRs we reopen this branch with proper naming convention under the `dev` branch. @cfkawa please respond to comment this as soon as possible so that we can take appropriate action and move forward

**Comment by cfkawa** [comment]
If you want to close the branch you may.

**Comment by dorukaks** [comment]
Closing the PR without merging. The branch will be reopened with proper naming convention from `dev`

**Pull request closed without merging**
